%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\filip\OneDrive\Desktop\Lavori\Miei\PROD_TFP\al_TFP_lagged.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 30-Sep-2024 17:48:29

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:D12";

% Specify column names and types
opts.VariableNames = ["b", "u", "d", "lag"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Import the data
tbl = readtable("C:\Users\filip\OneDrive\Desktop\Lavori\Miei\PROD_TFP\al_TFP_lagged.xlsx", opts, "UseExcel", false);

%% Convert to output type
b = tbl.b;
u = tbl.u;
d = tbl.d;
lag = tbl.lag;

%% Clear temporary variables
clear opts tbl


%% Plots beta

close all 

g1 = figure('Name', 'al_TFP_lagged'); % Set size

% Define your x values
x = lag; % Assuming lag is already defined

% Define the lower and upper bounds
curve1 = d; % Lower bound (constant value d)
curve2 = u; % Upper bound (constant value u)
hold on;

% Plot the upper and lower curves
plot(x, u, 'k--', 'LineWidth', 1);
plot(x, d, 'k--', 'LineWidth', 1);

% Shade the area between the upper and lower curves
for i = 1:length(x)-1
    % Define the x and y coordinates of the polygon
    x_fill = [x(i), x(i+1), x(i+1), x(i)];
    y_fill = [d(i), d(i+1), u(i+1), u(i)];
    
    % Fill the area
   FILL= fill(x_fill, y_fill,  [0.5 0.5 0.5], 'FaceAlpha', 0.5, 'EdgeColor', 'none'); % Adjust color and transparency
end

hold on
h1=plot(x,b,'k-')

h = yline(0, 'k', 'LineWidth', 1, 'HandleVisibility','off');
box on; % Ensure the box is drawn around the plot

legend([h, FILL], {'Estimate', '99\% CI'}, 'Interpreter', 'latex');

% Add labels and title
xlabel('Lag', 'Interpreter', 'latex');
% ylabel('Estimate', 'Interpreter', 'latex');
% title('Shaded Area Between Upper and Lower Curves', 'Interpreter', 'latex');
legend show; % Show legend for clarity
set(gca,'Color','none')
ylim padded

print(g1,'al_TFP_lagged','-depsc',  '-painters','-r600')

