clear all
close all

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\filip\OneDrive\Desktop\Lavori\Miei\PROD_TFP\al_TFP_pred.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 25-Sep-2024 18:30:56

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 10);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:J12811";

% Specify column names and types
opts.VariableNames = ["year1", "rtfpna", "CS", "country_id", "CS_betareg", "CS_betareg_Y", "CS_betareg_YC", "CS_fracreg", "CS_fracreg_Y", "CS_fracreg_YC"];
opts.VariableTypes = ["double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "country_id", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\Users\filip\OneDrive\Desktop\Lavori\Miei\PROD_TFP\al_TFP_pred.xlsx", opts, "UseExcel", false);

%% Convert to output type
year1 = tbl.year1;
rtfpna = tbl.rtfpna;
CS = tbl.CS;
country_id = tbl.country_id;
CS_betareg = tbl.CS_betareg;
CS_betareg_Y = tbl.CS_betareg_Y;
CS_betareg_YC = tbl.CS_betareg_YC;
CS_fracreg = tbl.CS_fracreg;
CS_fracreg_Y = tbl.CS_fracreg_Y;
CS_fracreg_YC = tbl.CS_fracreg_YC;

%% Clear temporary variables
clear opts tbl


%% creo bisettrice

x = 0:0.001:1;

% The bisettrice is y = x
y = x;

orange_color = [0.9290 0.6940 0.1250]; % Orange color


%% Plots Scatter

close all 

g1 = figure('Name', 'al_TFP_pred'); % Set size

% Scatter plots with transparency

scatter(CS, CS_betareg_YC, 'k', 'filled', 'MarkerFaceAlpha', 0.9)
hold on
scatter(CS, CS_fracreg_YC, 'filled', 'MarkerFaceColor', orange_color, 'MarkerFaceAlpha', 0.1);


% Plot for line (not visible in the legend)
plot(x, y, 'k', 'LineWidth', 1, 'HandleVisibility', 'off');

% Create handles for the legend
h1 = scatter(nan, nan, 'k', 'filled', 'MarkerFaceAlpha', 1);  % Full opacity for legend
h2 = scatter(nan, nan, 'filled', 'MarkerFaceColor', orange_color, 'MarkerFaceAlpha', 1); % Full opacity for legend


legend([h1, h2], {'$\widehat{\alpha}$, Beta regression', '$\widehat{\alpha}$, Fractional regression'}, ...
    'Interpreter', 'latex', 'Location', 'best')

xlim([0 1]) 
set(gca, 'Color', 'none')

xlabel('$\alpha$', 'Interpreter', 'latex');  
ylabel('$\widehat{\alpha}$', 'Interpreter', 'latex'); 
box on; % Ensure the box is drawn around the plot
set(gca,'Color','none')
% Save the figure in PDF format
print(g1, 'al_TFP_pred', '-dpdf', '-painters', '-r600')
